# create-pipeline.yaml
trigger: none

pool:
  vmImage: 'ubuntu-latest'

variables:
  location: 'centralindia'

stages:

- stage: Bootstrap
  displayName: '1. Bootstrap Terraform Backend'
  jobs:
  - job: Bootstrap
    steps:
    - template: templates/install-terraform.yml
    - task: AzureCLI@2
      displayName: 'Terraform Init - Bootstrap'
      inputs:
        azureSubscription: 'VSPro-Azure-Connection'
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |
          cd terraform-bootstrap
          terraform init

    - task: AzureCLI@2
      displayName: 'Terraform Apply - Backend Storage'
      inputs:
        azureSubscription: 'VSPro-Azure-Connection'
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |
          cd terraform-bootstrap
          terraform apply -auto-approve -var="location=$(location)"

- stage: Infrastructure
  displayName: '2. Create AKS Infrastructure'
  dependsOn: Bootstrap
  jobs:
  - job: TerraformAKS
    steps:
    - template: templates/install-terraform.yml
    - task: AzureCLI@2
      displayName: 'Terraform Init - Main'
      inputs:
        azureSubscription: 'VSPro-Azure-Connection'
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |
          cd terraform-prod
          terraform init

    - task: AzureCLI@2
      displayName: 'Terraform Apply - AKS + Nodepool + IP'
      inputs:
        azureSubscription: 'VSPro-Azure-Connection'
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |
          cd terraform-prod
          terraform apply -auto-approve \
            -var="resource_group_name=$(ResourceGroupName)" \
            -var="location=$(location)" \
            -var="user_nodepool_enabled=true"