# create-pipeline.yaml
trigger: none

pool:
  vmImage: 'ubuntu-latest'

variables:
  location: 'centralindia'

stages:

- stage: Bootstrap
  displayName: '1. Bootstrap Terraform Backend'
  jobs:
  - job: Bootstrap
    steps:
    - template: templates/install-terraform.yaml
    - task: AzureCLI@2
      displayName: 'Terraform Init - Bootstrap'
      inputs:
        azureSubscription: 'VSPro-Azure-Connection'
        scriptType: 'pscore'
        scriptLocation: 'inlineScript'
        inlineScript: |
          cd terraform-bootstrap
          terraform init

    - task: AzureCLI@2
      displayName: 'Create Backend Storage if not exists'
      inputs:
        azureSubscription: 'VSPro-Azure-Connection'
        scriptType: 'pscore'
        scriptLocation: 'inlineScript'
        inlineScript: |
          cd terraform-bootstrap
          
          # Check if storage account already exists
          $accountExists = az storage account show --name $(StorageAccountName) --resource-group $(ResourceGroupName) --query "name" -o tsv 2>$null
          
          if ($accountExists) {
            Write-Host "Storage account '$(StorageAccountName)' already exists. Skipping creation."
          } else {
            Write-Host "Storage account does not exist. Creating it..."
            terraform apply -auto-approve -var="resource_group_name=$(ResourceGroupName)" -var="location=$(location)" -var="storage_account_name=$(StorageAccountName)"
          }

- stage: Infrastructure
  displayName: '2. Create AKS Infrastructure'
  dependsOn: Bootstrap
  jobs:
  - job: TerraformAKS
    steps:
    - template: templates/install-terraform.yaml
    - task: AzureCLI@2
      displayName: 'Terraform Init - Main'
      inputs:
        azureSubscription: 'VSPro-Azure-Connection'
        scriptType: 'pscore'
        scriptLocation: 'inlineScript'
        inlineScript: |
          cd terraform-cicd
          terraform init -backend-config="resource_group_name=$(ResourceGroupName)" -backend-config="storage_account_name=$(StorageAccountName)" -backend-config="container_name=tfstate" -backend-config="key=terraform.tfstate"

    - task: AzureCLI@2
      displayName: 'Terraform Apply - AKS + Nodepool + IP'
      inputs:
        azureSubscription: 'VSPro-Azure-Connection'
        scriptType: 'pscore'
        scriptLocation: 'inlineScript'
        inlineScript: |
          cd terraform-cicd
          terraform apply -auto-approve -var="resource_group_name=$(ResourceGroupName)" -var="location=$(location)" -var="user_nodepool_enabled=true" -var="storage_account_name=$(StorageAccountName)"