trigger:
  - none

pool:
  vmImage: 'ubuntu-latest'

variables:
  dockerHubUsername: 'p47r1ck75'
  imageTag: '$(Build.BuildId)'
  
  environment: 'dev'
  namespace: '$(environment)'
  model: 'phi3:mini'

stages:
- stage: Build
  displayName: '2. Build & Push Docker Images'
  jobs:
  - job: BuildImages
    steps:

    - script: |
        echo $(dockerHubPassword) | docker login -u $(dockerHubUsername) --password-stdin
      displayName: '🔑 Docker Login to Docker Hub'

    - task: Docker@2
      displayName: 'Build & Push llm-adapter'
      inputs:
        command: buildAndPush
        repository: '$(dockerHubUsername)/llm-adapter'
        dockerfile: 'llm-adapter/Dockerfile'
        tags: '$(imageTag),latest'

    - task: Docker@2
      displayName: 'Build & Push sentiment-api'
      inputs:
        command: buildAndPush
        repository: '$(dockerHubUsername)/sentiment-api'
        dockerfile: 'sentiment-api/Dockerfile'
        tags: '$(imageTag),latest'

- stage: Deploy
  displayName: '3. Deploy to AKS'
  dependsOn: Build
  jobs:
  - deployment: Deploy
    displayName: 'Deploy'
    environment: '$(environment)'
    strategy:
      runOnce:
        deploy:
          steps:
          - script: |
              echo "Adding Traefik Helm repository..."
              helm repo add traefik https://traefik.github.io/charts
              helm repo update
              echo "Traefik repo added and updated"
            displayName: 'Add Traefik Helm Repo'

          - task: HelmDeploy@0
            displayName: 'Deploy Traefik'
            inputs:
              connectionType: 'Kubernetes Service Connection'
              kubernetesServiceConnection: 'AKS-VSPro-Connection'
              namespace: 'ingress'
              command: 'upgrade'
              chartType: 'Name'
              chartName: 'traefik/traefik'
              releaseName: 'traefik'
              arguments: '--install --atomic --create-namespace --set service.spec.loadBalancerIP=$(TerraformOutput.traefik_public_ip)'          

          - task: Bash@3
            displayName: 'Create Kubernetes Namespace'
            inputs:
              targetType: 'inline'
              script: |
                echo "Creating namespace: $(namespace)"
                kubectl create namespace $(namespace) --dry-run=client -o yaml | kubectl apply -f - --validate=false

          - task: KubernetesManifest@1
            displayName: 'Deploy Application'
            inputs:
              action: 'deploy'
              kubernetesServiceConnection: 'AKS-VSPro-Connection'
              namespace: '$(namespace)'
              manifests: |
                k8s/sentiment-configmap.yaml
                k8s/ollama-deployment.yaml
                k8s/llm-adapter-deployment.yaml
                k8s/sentiment-api-deployment.yaml
                k8s/sentiment-api-service.yaml
                k8s/sentiment-api-ingress.yaml