service:
  enabled: true
  type: LoadBalancer
  spec:
    loadBalancerIP: "__AKS_PUBLIC_IP__"
    externalTrafficPolicy: Local

  annotations:
    service.beta.kubernetes.io/azure-load-balancer-resource-group: "__AKS_RESOURCE_GROUP_NAME__"
    service.beta.kubernetes.io/azure-load-balancer-pip-name: "__AKS_PIP_NAME__"